crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movie.urls")),
]

crud/movie/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.list, name="list"),
    path("new/", views.new, name="new"),
    path("<int:id>/", views.detail, name="detail"),
    path("<int:id>/update/", views.update, name="update"),
    path("<int:id>/delete/", views.delete, name="delete"),
    
    path("<int:id>/comment/", views.comment, name="comment"),
]

crud/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
        
class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    

crud/movie/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
# Create your views here.
def list(request):
    movies = Movie.objects.all()
    return render(request, "movie/list.html", {"movies":movies})
    
    
def new(request):
    if request.method == "POST":
        title = request.POST.get("title")
        title_en = request.POST.get("title_en")
        audience = request.POST.get("audience")
        open_date = request.POST.get("open_date")
        genre = request.POST.get("genre")
        watch_grade = request.POST.get("watch_grade")
        score = request.POST.get("score")
        poster_url = request.POST.get("poster_url")
        description = request.POST.get("description")
        
        Movie.objects.create(title=title,title_en=title_en, audience=audience,open_date=open_date,
        genre=genre, watch_grade=watch_grade, score=score, poster_url=poster_url, description=description)
        
        return redirect("movies:list")
    
    else:
        return render(request,"movie/new.html")
        
    
def detail(request,id):
    movie = Movie.objects.get(id=id)
    return render(request, "movie/detail.html", {"movie":movie})
    
def update(request,id):
    
    movie = Movie.objects.get(id=id)
    
    if request.method == "POST":
        title = request.POST.get("title")
        title_en = request.POST.get("title_en")
        audience = request.POST.get("audience")
        open_date = request.POST.get("open_date")
        genre = request.POST.get("genre")
        watch_grade = request.POST.get("watch_grade")
        score = request.POST.get("score")
        poster_url = request.POST.get("poster_url")
        description = request.POST.get("description")
        
        movie.title =title
        movie.title_en = title_en
        movie.audience = audience
        movie.open_date = open_date
        movie.genre = genre
        movie.watch_grade = watch_grade
        movie.score = score
        movie.poster_url = poster_url
        movie.description = description
        
        movie.save()
        
        return redirect("movies:detail", id)
        
    else:
        return render(request, "movie/update.html", {"movie":movie})
        

def delete(request, id):
    movie = Movie.objects.get(id=id)
    movie.delete()
    return redirect("movies:list")
    
def comment(request, id):
    movie = Movie.objects.get(id=id)
    content = request.POST.get("content")
    
    Comment.objects.create(movie=movie,content=content)
    return redirect("movies:detail", id)

crud/movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'movies:list' %}">Movie</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'movies:list' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:new' %}">영화등록</a>
          </li>
          
        </ul>
      </div>
    </nav>
    {% block bb %}
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

crud/movie/templates/movie/detail.html
{% extends "movie/base.html" %}

{% block bb %}
    <h1>{{movie.title}}</h1>
    <h3>{{movie.title_en}}</h3>
    <img src="{{movie.poster_url}}" alt="{{movie.poster_url}}" width="175" height="250">
    <h3>관객 : {{movie.audience}}</h3>
    <h3>개봉 : {{movie.open_date}}</h3>
    <h3>장르 : {{movie.genre}}</h3>
    <h3>연령 : {{movie.watch_grade}}</h3>
    <h3>평점 : {{movie.score}}</h3>
    <h5>상세 : {{movie.description}}</h5>

    
    <a href="{% url 'movies:list' %}">목록</a> <br>
    <a href="{% url 'movies:update' movie.id %}">수정하기</a><br>
    <a href="{% url 'movies:delete' movie.id %}">삭제하기</a>
    
    <hr>
    {% for comment in movie.comment_set.all %}
        
        <h5>{{comment.content}}</h5>
    {% endfor %}
    
    
    <form action="{% url 'movies:comment' movie.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="content"/>
        <input type="submit"/>
    </form>
    
{% endblock %}

crud/movie/templates/movie/list.html
{% extends "movie/base.html" %}

{% block bb %}
    
    <div class="container"> 
        <center><h2 class="toto">영화리스트</h2></center>
        <div class="row"> 
        {% for movie in movies %}
            <div class="card col-3" style="width: 18rem;">
              <div class="card-body">
                <img src="{{movie.poster_url}}" class="card-img-top" alt="{{movie.poster_url}}">
                <h4 class="card-title"><a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
                <span class="badge badge-info">{{movie.score}}</span></h4>
                <hr width="100%" noshade/>
              </div>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}

crud/movie/templates/movie/new.html
{% extends "movie/base.html" %}

{% block bb %}

<h1>여기는 글작성!</h1>

    
    
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label>영화제목</label>
        <input type="text" class="form-control" placeholder="title" name="title"/>
      </div>
      
      <div class="form-group">
        <label>영문제목</label>
        <input type="text" class="form-control" placeholder="title_en" name="title_en"/>
      </div>
      
      <div class="form-group">
        <label>관객수</label>
        <input type="number" class="form-control" placeholder="audience" name="audience"/>
      </div>
      
      <div class="form-group">
        <label>개봉일</label>
        <input type="date" class="form-control" placeholder="open_date" name="open_date"/>
      </div>
      
      <div class="form-group">
        <label>장르</label>
        <input type="text" class="form-control" placeholder="genre" name="genre"/>
      </div>
      
      <div class="form-group">
        <label>연령제한</label>
        <input type="text" class="form-control" placeholder="watch_grade" name="watch_grade"/>
      </div>
      
      <div class="form-group">
        <label>점수</label>
        <input type="number" step="0.01" class="form-control"  placeholder="score" name="score"/>
      </div>
      
      <div class="form-group">
        <label>포스터url</label>
        <input type="text"class="form-control" placeholder="poster_url" name="poster_url"/>
      </div>
      
      <div class="form-group">
          <label>상세설명</label>
          <textarea name ="description" class="form-control" cols="40" rows="8"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  
  
{% endblock %}

crud/movie/templates/movie/update.html
{% extends "movie/base.html" %}

{% block bb %}

<h1>여기는 수정!</h1>

    
    
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label>title</label>
        <input type="text" class="form-control" placeholder="title" name="title" value="{{movie.title}}"/>
      </div>
      
      <div class="form-group">
        <label>title_en</label>
        <input type="text" class="form-control" placeholder="title_en" name="title_en" value="{{movie.title_en}}"/>
      </div>
      
      <div class="form-group">
        <label>audience</label>
        <input type="number" class="form-control" placeholder="audience" name="audience" value="{{movie.audience}}"/>
      </div>
      
      <div class="form-group">
        <label>open_date</label>
        <input type="date" class="form-control" placeholder="open_date" name="open_date" value="{{movie.open_date|date:'Y-m-d'}}"/>
      </div>
      
      <div class="form-group">
        <label>genre</label>
        <input type="text" class="form-control" placeholder="genre" name="genre" value="{{movie.genre}}"/>
      </div>
      
      <div class="form-group">
        <label>watch_grade</label>
        <input type="text" class="form-control" placeholder="watch_grade" name="watch_grade" value="{{movie.watch_grade}}"/>
      </div>
      
      <div class="form-group">
        <label>score</label>
        <input type="number" step="0.01" class="form-control"  placeholder="score" name="score" value="{{movie.score}}"/>
      </div>
      
      <div class="form-group">
        <label>poster_url</label>
        <input type="text"class="form-control" placeholder="poster_url" name="poster_url" value="{{movie.poster_url}}" />
      </div>
      
      <div class="form-group">
          <label>description</label>
          <textarea name ="description" class="form-control" cols="40" rows="8" >{{movie.description}}</textarea>
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  
  
{% endblock %}